<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsESRaQ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsESRaQ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXsESRaQ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXsESRaQ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXsESRaQ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XsESRaQ',
    'container.build_id' => 'be2e6462',
    'container.build_time' => 1543954510,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXsESRaQ');
